import '.././globals.css';

import { ClerkLoaded, ClerkLoading, ClerkProvider } from '@clerk/nextjs';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children}){
    return(
        <ClerkProvider>
        <html lang='en'>
           <body>
            <ClerkLoading>
                loader
            </ClerkLoading>   
             {children}
           </body>
        </html>
        </ClerkProvider>
    )
}